.TH EXCHANGE "1" "2020-08-07"
.SH NAME
exchange \- exchange (swap) two files
.SH SYNOPSIS
.B exchange
.RI [ OPTIONS ]... " PATH1 PATH2"
.SH DESCRIPTION
Swap the filenames of
.I PATH1
and
.IR PATH2 .
Each of
.I PATH1
and
.I PATH2
may be any kind of file, including directory.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR mv (1),
.BR rename (2).
